version: '3.8'

services:
  dev-admin-frontend:
    container_name: da-admin-frontend
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
      