FROM node:18-alpine
ENV NODE_ENV=production
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install --production --silent && mv node_modules ../
RUN npm install -g serve
RUN npm install -g sharp
COPY . .
EXPOSE 3001
RUN chown -R node /usr/src/app
USER node
RUN npm run build
CMD ["serve", "-s", "build", "-l", "3001"]
