version: '3.4'

services:
  da-admin:
    container_name: da-admin-frontend
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - "3001:3001"
